version: "3"

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/uploads
    expose:
      - 8000
    env_file:
      - ./env/.env.prod
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    env_file:
      - ./env/.env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/uploads
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
