version: "3"

services:
  app:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./app:/user/src/app
    ports: 
      - 8000:8000
    env_file: 
      - ./app/.env
