# Generated by Django 2.2.5 on 2021-01-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='status',
            field=models.CharField(choices=[('not started', 'Not started'), ('in progress', 'In progress'), ('complete', 'Complete')], default='in progress', max_length=20),
        ),
    ]
