# Generated by Django 2.2.5 on 2021-01-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_work_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='created_at',
            field=models.DateField(),
        ),
    ]
